export { default as profile } from "./profile.jpg"
export { default as github } from "./github.png"
export { default as linkedin } from "./linkedin.png"
export { default as twitter } from "./twitter.png"
export { default as ecommerce } from "./ecommerce.png"
export { default as weather } from "./weather.png"
export { default as portfolio } from "./portfolio.png"
export { default as taskManager } from "./task-manager.png"